---
- name: Check if VM already exists
  hosts: all
  vars_files:
    - vm_vars.yml
  handlers:
    - include: handlers/vmware.yml
  tasks: 
    - name: Check VM path
      stat: path='{{ vm_safe_dst_full_path }}'
      register: vm_exists
      changed_when: False
    - name: Fail if VM path exists
      fail: msg="VM already exists.  Please set vm_overwrite variable to any value to overwrite the existing VM"
      when: (vm_exists.stat.isdir is defined) and (vm_overwrite is not defined)
    - name: Get VMX path if existing VM is running
      shell: "'{{ vmrun_path }}' list | grep -F '{{ vm_safe_dst_full_path }}' || true"
      register: existing_vmx_path
      when: vm_exists.stat.isdir is defined
      changed_when: False
    - name: Stop VM if it is running
      shell: "'{{ vmrun_path }}' stop '{{ existing_vmx_path.stdout }}'"
      when: existing_vmx_path is defined and existing_vmx_path.stdout != ""
    - name: Pause to allow VM to stop cleanly
      pause: seconds=3
      when: existing_vmx_path is defined and existing_vmx_path.stdout != ""
    - name: Remove existing VM path
      file: path='{{ vm_safe_dst_full_path }}' state=absent
    - name: Create VM path
      file: path='{{ vm_safe_dst_full_path }}' state=directory
    - name: Extract OVA using ovftool
      command: "'/{{ ovftool_path.stdout }}' '{{ ova_source }}' '{{ vm_vmx_path }}'"
    